/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio_s4n;

import javax.swing.JOptionPane;

/**
 *
 * @author MyA
 */
public class Ejercicio_S4N extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio_S4N
     */
    V_Campo V_Campo  = new V_Campo(); 
    public Ejercicio_S4N() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Resultado = new javax.swing.JTextArea();
        txt_Num = new javax.swing.JTextField();
        But_Calcular = new javax.swing.JButton();
        But_Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número a calcular");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("<html>Ejercicio:<p><p>\"Write a program that prints the numbers from 1 to 100.<p>"
            + "But for multiples of three print \"Fizz\" instead of the number and for <p>" +
            "the multiples of five print \"Buzz\". For numbers which are multiples<p>" +
            "of both three and five print \"FizzBuzz\".\" <html>");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Resultado");

        txt_Resultado.setEditable(false);
        txt_Resultado.setColumns(20);
        txt_Resultado.setRows(5);
        jScrollPane1.setViewportView(txt_Resultado);

        txt_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NumActionPerformed(evt);
            }
        });
        txt_Num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NumKeyTyped(evt);
            }
        });

        But_Calcular.setLabel("Calcular");
        But_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_CalcularActionPerformed(evt);
            }
        });

        But_Limpiar.setText("Limpiar");
        But_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(But_Calcular)
                                .addComponent(txt_Num))
                            .addComponent(But_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(But_Calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(But_Limpiar)
                        .addGap(18, 18, 18)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NumActionPerformed

    }//GEN-LAST:event_txt_NumActionPerformed

    private void txt_NumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NumKeyTyped
        V_Campo.Numero(evt);
    }//GEN-LAST:event_txt_NumKeyTyped

    private void But_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_CalcularActionPerformed

        txt_Resultado.setText(null);
        if (txt_Num.getText().length() == 0) {
            txt_Resultado.append("No ha ingresado ningun dato");
        } else {
            int num = Integer.parseInt(txt_Num.getText());
            int limite = 100;
            if (num >= 1 && num <= limite) {

                for (int i = 0; i <= limite; i++) {

                    if (i % num == 0) {
                        if (i % 3 == 0 && i % 5 == 0) {
                            txt_Resultado.append("FizzBuzz\n");
                        } else {
                            if (i % 3 == 0) {
                                txt_Resultado.append("Fizz\n");
                            } else {
                                if (i % 5 == 0) {
                                    txt_Resultado.append("Buzz\n");
                                } else {
                                    txt_Resultado.append(String.valueOf(i) + "\n");
                                }
                            }
                        }
                    }
                }
            } else {
                txt_Resultado.append("Verificar:\nSolo números comprendidos entre 1 y 100");
            }
        }
    }//GEN-LAST:event_But_CalcularActionPerformed

    private void But_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_LimpiarActionPerformed
        txt_Num.setText(null);
        txt_Resultado.setText(null);
    }//GEN-LAST:event_But_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_S4N.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_S4N.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_S4N.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_S4N.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio_S4N().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton But_Calcular;
    private javax.swing.JButton But_Limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Num;
    private javax.swing.JTextArea txt_Resultado;
    // End of variables declaration//GEN-END:variables
}
